services:
  db:
    container_name: Peaceful-Farm-DB
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


  web:
    container_name: Peaceful-Farm-WEB
    image: peaceful-farm
    build: ./web
    restart: always
    ports:
      - ${PEACEFUL_FARM_SERVER_PORT}:${PEACEFUL_FARM_SERVER_PORT}
    volumes:
      - ./web/app:/app:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PEACEFUL_FARM_SERVER_PORT: ${PEACEFUL_FARM_SERVER_PORT}


  php:
    container_name: Peaceful-Farm-PHP
    image: peaceful-farm-php-exec
    build: ./php
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
      - web


  node:
    container_name: Peaceful-Farm-NODE
    image: peaceful-farm-node-exec
    build: ./node
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
      - web

volumes:
  mysql_data: